name: finance_tracker
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  uuid: ^3.0.6
  cupertino_icons: ^1.0.8
  fl_chart: ^1.0.0
  csv: ^5.0.0
  pdf: ^3.8.1
  printing: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  hive_generator: ^1.1.3
  build_runner: ^2.3.3

flutter:

  
  uses-material-design: true

  
